openapi: 3.0.3 # version of the specification
info:
  title: CMDB-OPEN-API-COLLECTION
  version: 1.0.0
  description: Service API specification to support Database operations

servers:
  - url: '{protocol}://{ip}:{port}/{base-api}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      ip:
        enum:
          - localhost
          - 34.199.12.114
        default: localhost
      port:
        enum:
          - '6057'
          - '5057'
        default: '6057'
      base-api:
        enum:
          - api
        default: api

tags:
  - name: Organization
    description: perform CRUD operations on organization table
  - name: Department
    description: perform CRUD operations on department table
  - name: CloudEnvironment
    description: perform CRUD operations on cloud-environment table

paths:
  /organizations:
    get:
      tags:
        - Organization
      summary: Fetch list of organizations
      operationId: getOrganizationList
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
    post:
      tags:
        - Organization
      summary: Add organization
      operationId: addOrganization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDTO'
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
    patch:
      tags:
        - Organization
      summary: Update organization
      operationId: updateOrganization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDTO'
        201:
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /organizations/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
    get:
      tags:
        - Organization
      summary: Fetch an organization of given id
      operationId: getOrganization
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /organizations/search:
    get:
      tags:
        - Organization
      summary: Search organizations data
      operationId: search
      parameters:
        - name: organizationDto
          in: query
          required: false
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /departments:
    get:
      tags:
        - Department
      summary: Fetch list of departments
      operationId: getDepartmentList
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DepartmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
    post:
      tags:
        - Department
      summary: Add department
      operationId: addDepartment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepartmentDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentDTO'
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
    patch:
      tags:
        - Department
      summary: Update department
      operationId: updateDepartment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepartmentDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentDTO'
        201:
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /departments/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
    get:
      tags:
        - Department
      summary: Fetch a department of given id
      operationId: getDepartment
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /departments/search:
    get:
      tags:
        - Department
      summary: Search departments data
      operationId: searchDepartment
      parameters:
        - name: departmentDto
          in: query
          required: false
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DepartmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /cloud-environments:
    get:
      tags:
        - CloudEnvironment
      summary: Fetch list of CloudEnvironments
      operationId: getCloudEnvironmentList
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CloudEnvironmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
    post:
      tags:
        - CloudEnvironment
      summary: Add cloud-environment
      operationId: addCloudEnvironment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloudEnvironmentDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudEnvironmentDTO'
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudEnvironmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
    patch:
      tags:
        - CloudEnvironment
      summary: Update cloud-environment
      operationId: updateCloudEnvironment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloudEnvironmentDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudEnvironmentDTO'
        201:
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudEnvironmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /cloud-environments/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
    get:
      tags:
        - CloudEnvironment
      summary: Fetch a cloud-environment of given id
      operationId: getCloudEnvironment
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudEnvironmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
  /cloud-environments/search:
    get:
      tags:
        - CloudEnvironment
      summary: Search cloud-environments data
      operationId: searchCloudEnvironment
      parameters:
        - name: cloudEnvironmentDto
          in: query
          required: false
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudEnvironmentDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CloudEnvironmentDTO'
        404:
          description: "Service Not found"
        500:
          description: "Internal Server Error"
components:
  schemas:
    OrganizationDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        createdBy:
          type: string
        updatedBy:
          type: string
        createdOn:
          type: string
        updatedOn:
          type: string
        departments:
          type: array
          items:
            $ref: '#/components/schemas/DepartmentDTO'
    DepartmentDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        status:
          type: string
        createdBy:
          type: string
        updatedBy:
          type: string
        createdOn:
          type: string
        updatedOn:
          type: string
        organizationId:
          type: integer
          format: int64
    CloudEnvironmentDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        accountId:
          type: string
        cloud:
          type: string
        displayName:
          type: string
        roleArn:
          type: string
        externalId:
          type: string
        status:
          type: string
        createdBy:
          type: string
        updatedBy:
          type: string
        createdOn:
          type: string
        updatedOn:
          type: string
        departmentId:
          type: integer
          format: int64